Upgrade Node to 16
juliangruber/approve-pull-request-action pull request #37
Opened 2022-11-23 23:26 UTC by skeep-exogee

Should we upgrade not to the latest as getting this message when running the action:

`Node.js 12 actions are deprecated.`

2022-11-23 23:51 UTC, juliangruber requested changes

2022-11-23 23:51 UTC, juliangruber commented on package.json
> +  "version": "2.0.2",
could you please undo this line? I'm going to bump the version as part of my release process
```suggestion
  "version": "2.0.1",
```

2022-11-24 00:24 UTC, skeep-exogee commented
Made that change thanks 👍

2022-11-24 12:07 UTC, juliangruber approved these changes

2022-11-24 12:07 UTC, merged

2022-11-24 12:09 UTC, juliangruber commented
Thank you!

https://github.com/juliangruber/approve-pull-request-action/releases/tag/v2.0.2